### ISSUE TITLE
index.html 2번째 article 수정 및 반응형으로 만들기

### ISSUE THREAD

**Issue by huimang2** [huimang2/html#38]
### 1. 밑줄 없애고 색상 변경
https://github.com/huimang2/html/blob/780e0dae4986a1d64563e0a45a7da9f91a5b68ca/project/drclio/index.html#L140-L168
* 뉴스 타이틀에 밑줄을 없애고 색상을 변경해주세요.

### 2. 반응형으로 만들기
https://github.com/huimang2/html/blob/780e0dae4986a1d64563e0a45a7da9f91a5b68ca/project/drclio/index.html#L107-L170
article을 반응형으로 만들어 주세요.
* 기본 컨텐츠 width: 1200px;
* 스크린 크기가 1250 이하일때 컨텐츠 width: 1000px;

**Comment by Dana-Moon** [comment]
끝났습니다.
