### ISSUE TITLE
index.html 첫번째 article 애니메이션 효과 넣기

### ISSUE THREAD

**Issue by huimang2** [huimang2/html#41]
https://github.com/huimang2/html/blob/528cefdd74c918e9dfba5a89de7e4685cf976b76/project/drclio/index.html#L91-L104

캐러셀에 애니메이션 효과를 넣어주세요.
슬라이드 효과를 넣어도 되고 페이드 인아웃 효과를 넣어도 됩니다.
이미지 순서도 상관 없습니다.

**Comment by Dana-Moon** [comment]
배너 좌우 버튼 만들기까지 완료하였음.
